version: '3.8'
services:
  frontend:
    image: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
  backend:
    image: backend
    build:
      context: ./iat_core/
      dockerfile: Dockerfile
    volumes:
      - ./iat_core:/app
    ports:
      - "8000:8000" 
