version: '1'
services:
  frontend:
    image: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/app/app
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
  backend:
    image: backend
    build:
      context: ./iat_core/
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./iat_core:/iat_core
    env_file:
      - ./.env
    ports:
      - "8000:8000"
  db:
    image: db
    build:
      context: ./iat_core/database/
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./iat_core/database/data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
